### ISSUE TITLE
Include publisher in search

### ISSUE THREAD

**Issue by LeAchim59** [Larian77/Openbiblio#19]
classes/BiblioSearchQuery.php

Um auch nach Verlag suchen zu können, darf 'a' und 'b' nicht in der Abfrage enthalten sein:

To include publisher in search remove 'a' and 'b' from join:

before:
`$join .= "and not (bf" . $i . ".tag = '260' and bf" . $i . ".subfield_cd in ('a', 'b', 'e', 'f', 'g')) ";`

new version:
`$join .= "and not (bf" . $i . ".tag = '260' and bf" . $i . ".subfield_cd in ('e', 'f', 'g')) ";`

**Comment by Larian77** [comment]
Das passt, habe aber die Felder angepasst, 260, aber nicht a, b, e, f, g hieß:
nimm aus 260 mit: Erscheinungsjahr (c), Name des Musik-Verlages (d)
nimm nicht mit: Erscheinungsort (a), Name des Verlages (b), Herstellungsort (e), Hersteller (f), Herstellungsjahr (g)
____
That fits, but I have adjusted the fields, 260, but not a, b, e, f, g means:
take from 260: Date of publication (c), Plates of publisher's number for music (d)
do not include: Place of publication (a), name of publisher (b), place of manufacture (e), manufacturer (f), Date of manufacture (g)

I have generally adapted this so that it takes the years and names with it, but not the places, i.e:
$join .= "and not (bf" . $i . ".tag = '260' and bf" . $i . ".subfield_cd in ('a', 'e')) ";

**Comment by LeAchim59** [comment]
Danke, das passt auch, bzw. ist besser.
